branches:
  except:
    - /dev.*/  # do not build dev branch

image:
  - Visual Studio 2017

platform:
  - x86

environment:
  VCPKG_ROOT: C:\tools\vcpkg
  VCPKG_TRIPLET: my-x86-windows-static

cache: c:\tools\vcpkg\installed\ -> .appveyor.yml  # cache the installed vcpkg packages

install:
  - echo set(VCPKG_TARGET_ARCHITECTURE x86) > %VCPKG_ROOT%\triplets\%VCPKG_TRIPLET%.cmake
  - echo set(VCPKG_CRT_LINKAGE dynamic) >> %VCPKG_ROOT%\triplets\%VCPKG_TRIPLET%.cmake
  - echo set(VCPKG_LIBRARY_LINKAGE static) >> %VCPKG_ROOT%\triplets\%VCPKG_TRIPLET%.cmake
  - echo set(VCPKG_PLATFORM_TOOLSET v141) >> %VCPKG_ROOT%\triplets\%VCPKG_TRIPLET%.cmake

  - vcpkg --triplet %VCPKG_TRIPLET% install boost-algorithm libiconv

build_script:
  - powershell scripts/generate.ps1 Debug
  - powershell scripts/build.ps1 Debug
  - powershell scripts/generate.ps1 Release
  - powershell scripts/build.ps1 Release
